### ISSUE TITLE
Dependency Issues

### ISSUE THREAD

**Issue by pand0rausa** [MooseDojo/apt2#22]
[!] Module 'responder' disabled. Dependency required: '['responder']'
....
[!] Module 'nmapbasescan' disabled. Dependency required: '['nmap', 'disabled']'

nmap is installed in Debian using the package manager but not found (/usr/bin/nmap). Need option to add in custom path, especially if compiled from source.
Responder path is in custom directory and not being detected when the config file is updated.

responder_path=/home/<user>/Applications/Windows/Responder/

**Comment by tatanus** [comment]
I just updated the code base to standardize the way that command paths are identified and used.   If APT2 can not find your instance of nmap or responder, either:

1) add those paths to your PATH
or
2) add the appropriate lines to default.cfg

You can add lines as follows:

[default_tool_paths]
responder=/usr/share/responder/Responder.py
nmap=/usr/bin/nmap


Please let me know if this does not work for you.

**Comment by pand0rausa** [comment]
Resolved the Responder issue. Still have the problem of nmap being disabled.

[!] Module 'nmapbasescan' disabled. Dependency required: '['nmap', 'disabled']'

pip install python-nmap
Requirement already satisfied (use --upgrade to upgrade): python-nmap in /usr/local/lib/python2.7/dist-packages

which nmap
/usr/bin/nmap

**Comment by tatanus** [comment]
That would be because the nmapbasescan module is hard coded as  "disabled" and thus will always be shown as disabled.  That is a deprecated module and needs to be removed.  I just have not gotten around to doing it yet.  But the other nmap based modules should still work fine.

**Comment by pand0rausa** [comment]
rgr
