### ISSUE TITLE
Naming issue with APT

### ISSUE THREAD

**Issue by julian-klode** [MooseDojo/apt2#27]
Hi,

I just saw this project today while searching for APT2. As you probably know there is a package manager called APT and there was an APT2 project writing a successor/alternative in C, which I started in Vala in 2009 and revived in C in 2011, but which is dormant now. Now it is mostly a source of ideas.

The name APT2 implies that this is the second generation of APT and can lead to confusion, especially if someone wants to end up packaging this for Debian-based distributions. Especially of course when APT reaches version 2.

It would be great if you could rename your project to avoid potential issues.

**Comment by acompton-r7** [comment]
sorry, I am pretty sure we are going to be keeping the name of APT2 for now, unless a great alternative can be decided on.
