### ISSUE TITLE
Metasploit Msgrpc error

### ISSUE THREAD

**Issue by mehdibob** [MooseDojo/apt2#29]
Hello,
I've tried all required trick but:
[!] Could not connect to Metasploit msgrpc service with the following parameters:
[!]      host     = [127.0.0.1]
[!]      port     = [55553]
[!]      user     = [msf]
[!]      password = [0000]
-----
In msfconsole :+1: 
msf > load msgrpc User=msf Pass=0000 ServerPort=55553
[*] MSGRPC Service:  127.0.0.1:55553 
[*] MSGRPC Username: msf
[*] MSGRPC Password: 0000
[*] Successfully loaded plugin: msgrpc
-----
Still get the same error, any suggestion?
msf > version
Framework: 4.14.11-dev
Console  : 4.14.11-dev

**Comment by tatanus** [comment]
I am looking in the reason for this.  I hope to be back to you on it shortly.

**Comment by tatanus** [comment]
Just to verify, you do have the msgrpc Python module installed correct?

**Comment by tatanus** [comment]
are you still experiencing the issue?

**Comment by mehdibob** [comment]
I've fixed the issu, I must specify User and Pass in load msgrpc, sorry.
I suggest to add RETREIVE PUBLIC IP ADRESS like this in framework.py:
....
from json import load
from urllib2 import urlopen
...
...
my_ip = load(urlopen('https://api.ipify.org/?format=json'))['ip']
        self.config['lhost'] = my_ip
....
It works perfectly, what you think?
Thanks

**Comment by tatanus** [comment]
I will look into adding a way to retrieve the current public IP.

Thank you

**Comment by acompton-r7** [comment]
sorry for the delay, but using a 3rd party  website like that is not the approach we would like to use.  We will continue to work to see if there is a way that we like to obtain the public ip, but that will be a separate issue ticket.  as a result I will be closing this one.
