### ISSUE TITLE
invalid syntax (apt2_whois.py, line 49)

### ISSUE THREAD

**Issue by ifly53e** [MooseDojo/apt2#31]
Running Kali 2017.1

./apt2.py -b
gives:
invalid syntax (apt2_whois.py, line 49)
see below.

line 49 is email=results['email']

looks normal to me so I don't know what is up...

root@kali:~/Desktop/apt2-master# ./apt2.py -b
[*] 
[*]       dM.    `MMMMMMMb. MMMMMMMMMM      
[*]      ,MMb     MM    `Mb /   MM   \      
[*]      d'YM.    MM     MM     MM   ____   
[*]     ,P `Mb    MM     MM     MM  6MMMMb  
[*]     d'  YM.   MM    .M9     MM MM'  `Mb 
[*]    ,P   `Mb   MMMMMMM9'     MM      ,MM 
[*]    d'    YM.  MM            MM     ,MM' 
[*]   ,MMMMMMMMb  MM            MM   ,M'    
[*]   d'      YM. MM            MM ,M'      
[*] _dM_     _dMM_MM_          _MM_MMMMMMMM 
[*] 
[*] 
[*] An Automated Penetration Testing Toolkit
[*] Written by: Adam Compton & Austin Lane
[*] Verion: 1.0.0
[!] Module 'responder' disabled:
[!]      Safety_Level (3) is below requirement: 4
[!] Module 'msf_tomcat_mgr_upload' disabled:
[!]      Safety_Level (3) is below requirement: 4
[!] Module 'hydrasmbpassword' disabled:
[!]      Safety_Level (2) is below requirement: 4
[!] Module 'msf_jboss_maindeployer' disabled:
[!]      Safety_Level (3) is below requirement: 4
invalid syntax (apt2_whois.py, line 49)
[!] Module 'apt2_whois' disabled.
[!] Module 'searchnfsshare' disabled:
[!]      Module Manually Disabled !!!
[*] Input Modules Loaded:	2
[*] Action Modules Loaded:	39
[*] Report Modules Loaded:	1

**Comment by tatanus** [comment]
should be fixed  now
