### ISSUE TITLE
apt2 only runs in menu mode

### ISSUE THREAD

**Issue by kwaber** [MooseDojo/apt2#37]
Hi
I am new to apt2, as a mattar of fact I just came across it, watched you presentation and instructions video, installed it and gave it my first try. I really liked the concept and would like to use it in my pentesting activities.

The problem I have is that when I run apt2 without '-b' and get the menu to configure my target the tool seems to work, what I mean by that is that I can see some meaningful output in my terminal and I can also see traffic sent to my target (btw the target is a VM based metasploitable2). 

(see the attached apt2 file)

However when I run it with '-b' option it simply quits right after the start
root@kali:~/Downloads/apt2# ./apt2.py -b -v -v -C misc/default.cfg --ip 192.168.56.102

(see the attached apt2-b file)

Also even in the first case (without -b) it does not seem it actually finds all the vulnerabilities. I ran it against a metasploitable 2 instance, which is full o vulns and it only found two as you can see in the apt2 output.

attached is also the default.cfg file.

What am I missing / doing wrong?
Thank you in advance for your help
Chris

[default.cfg.txt](https://github.com/MooseDojo/apt2/files/1268028/default.cfg.txt)
[apt2-b.txt](https://github.com/MooseDojo/apt2/files/1268030/apt2-b.txt)
[apt2.txt](https://github.com/MooseDojo/apt2/files/1268029/apt2.txt)
and ifconfig -a
root@kali:~/Downloads/apt2# ifconfig -a
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.11.139  netmask 255.255.255.0  broadcast 192.168.11.255
        ether 08:00:27:27:06:d4  txqueuelen 1000  (Ethernet)
        RX packets 134758  bytes 202669089 (193.2 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 49192  bytes 3393150 (3.2 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.56.102  netmask 255.255.255.0  broadcast 192.168.56.255
        ether 08:00:27:36:07:8e  txqueuelen 1000  (Ethernet)
        RX packets 42383  bytes 9223079 (8.7 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 55906  bytes 5970697 (5.6 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 54102  bytes 53727861 (51.2 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 54102  bytes 53727861 (51.2 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by acompton-r7** [comment]
the command you specified "./apt2.py -b -v -v -C misc/default.cfg --ip 192.168.56.102" is fine, but you still need to provide it an input file "-f" .  right now the only usable input file is a nmap ".xml" file.

I hope that helps.
