### ISSUE TITLE
Custom Output Location

### ISSUE THREAD

**Issue by Kolano** [MooseDojo/apt2#38]
APT2 currently ties it's output location to the user launching APT2 via...
`self.config["homeDir"] = expanduser("~")`

This can be problematic if running APT2 as a service, since then "~" expands to /root, which is not easily accessible. A service can be run as a specific user, but then APT2 seems to have alternate permission issues with file output per https://github.com/MooseDojo/apt2/issues/25.

**Comment by acompton-r7** [comment]
apt2 was never intended to be run as a service.  as an automated tool that runs on a input data file and continues to proccess until it is finished then finishes, I would not expect it to be run as a service.

If you have a valid use case for it to be used as a service, please let me know.
