### ISSUE TITLE
Can you include demo.xml?

### ISSUE THREAD

**Issue by theHackPot** [MooseDojo/apt2#48]
Hi,

Just going through some of the video presentations and there appears to be a demo.xml. I cannot see it when I get git clone, would it be possible to make this file available?

**Comment by acompton-r7** [comment]
demo.xml is just the XML output from an NMap scan of my home test lab.  As such , it would not do anyone any good to upload it to the git repo. If you want a demo.xml file of your own, simple run nmap and have it output to XML format and then use that.  Hope that helps.

**Comment by theHackPot** [comment]
yes it does, thank you
