### ISSUE TITLE
Error using the -b parameter

### ISSUE THREAD

**Issue by BraQwesi** [MooseDojo/apt2#53]
./apt2.py -v -v -b -f nmapscan/test.xml
usage: apt2.py [-h] [-C <config.txt>] [-f [<input file> [<input file> ...]]]
               [--target] [--ip <local IP>] [-v] [-s SAFE_LEVEL]
               [-x EXCLUDE_TYPES] [--listmodules]
apt2.py: error: unrecognized arguments: -b

**Comment by acompton-r7** [comment]
the -b option has been removed.
