### ISSUE TITLE
License

### ISSUE THREAD

**Issue by xorond** [MooseDojo/apt2#7]
Hello.

I'm planning to add in your tool into [ArchStrike](https://github.com/ArchStrike/ArchStrike) but I noticed your code has no license attached to it.

Is it possible for you to add in a license?

Thanks.

**Comment by tatanus** [comment]
we were just discussing this.  There should be a License added soon.

**Comment by tatanus** [comment]
A MIT License has been addd to the project.  Sorry for the delay.
